---
  - name: Install EPEL repository
    yum: name=epel-release state=latest

  - name: Install the nginx repository
    yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present

  - name: Install the latest version of nginx
    yum: name=nginx state=latest

  - name: Install the latest version of php-fpm
    yum: name=php-fpm state=latest

  - name: Configure php-fpm
    template: src=php.ini dest=/etc/php.ini
#    notify: Restart the php-fpm service

  - name: Restart the php-fpm service
    service: name=nginx state=restarted

  - name: Make directory for website contents
    file: path=/var/www/dylanmtaylor.com/html state=directory mode=0755

  - name: Remove Nginx default.conf
    file: path=/etc/nginx/conf.d/default.conf state=absent

  - name: Write the nginx configuration file
    template: src=nginx.conf dest=/etc/nginx/nginx.conf
#    notify: Restart the nginx service

  - name: Nginx sites-available directory
    file: path=/etc/nginx/sites-available state=directory mode=0775

  - name: Update the configuration files in sites-available
    synchronize: mode=push src=nginx-sites/ dest=/etc/nginx/sites-available
#    notify: Remove old Nginx sites-enabled directory

  - name: Remove old Nginx sites-enabled directory
    file: path=/etc/nginx/sites-enabled state=absent

  - name: Nginx sites-enabled directory
    file: path=/etc/nginx/sites-enabled state=directory mode=0755
#    notify:
#      - Enable all available sites
#      - Restart the nginx service

  - name: Enable all available sites
    shell: find /etc/nginx/sites-available/ -name '*.conf' -type f -exec ln -s {}  /etc/nginx/sites-enabled/ \;

  - name: Restart the nginx service
    service: name=nginx state=restarted

  - name: Enable nginx service at boot time
    service: name=nginx enabled=yes

  - name: Enable php-fpm service at boot time
    service: name=php-fpm enabled=yes
