# This simple GitLab CI file checks out and deploys my Ansible playbook
image: archlinux:latest

stages:
  - deploy
  - test

before_script:
  - pacman -Sy
  - pacman --noconfirm -S ansible git rsync openssh
  - mkdir ~/.ssh
  - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
  - chown -R $USER:$USER ~/.ssh
  - chmod 0600 ~/.ssh/*
  - chmod 0700 ~/.ssh/
  - echo "$IP_ADDRESS dylanmtaylor" >> /etc/hosts 

ansible_deploy:
  stage: deploy
  script:
    - git clone https://gitlab.com/dylanmtaylor/dylanmtaylor-ansible.git
    - cd dylanmtaylor-ansible
    - ansible-playbook playbook.yml

inspec:
  stage: test
  trigger:
    project: dylanmtaylor/dylanmtaylor-inspec
    branch: master
