---
- name: Provision my website to a new server
  hosts: servers
  remote_user: root # ubuntu on AWS
  become: yes

  roles:
    - users
    - nginx
    - gitcheckout
    - docker
    - cronjobs
    - utilities
    - security
    - gui
    - cleanup
