---
- name: Provision my website to a new server
  hosts: dylanmtaylor-server
  remote_user: root

  roles:
    - users
    - docker
    - nginx
    - security
    - utilities
    - gitcheckout
    - cronjobs
