---
- name: Provision 'Dylan M Taylor' to new CentOS 7 server
  hosts: dylanmtaylor-server
  remote_user: root

  tasks:
    - include: 'tasks/user/setup.yml'
    - include: 'tasks/secure/sshd.yml'
    - include: 'tasks/secure/firewall.yml'
    - include: 'tasks/nginx/install.yml'
    - include: 'tasks/utilities/install.yml'
    - include: 'tasks/git/checkout-data.yml'
    - include: 'tasks/cronjob/configure.yml'
    - include: 'tasks/swapfile/create.yml'
