---
- name: Provision 'Dylan M Taylor' to new server
  hosts: dylanmtaylor-server
  remote_user: root

  roles:
    - users
    - nginx
    - security
    - utilities
    - gitcheckout
    - cronjobs
    - lxqt-desktop
