---
- name: Provision 'Dylan M Taylor' to new CentOS 7 server
  hosts: dylanmtaylor-server
  remote_user: root

  roles:
    - users
    - security
    - nginx
    - utilities
    - gitcheckout
    - cronjobs
    - swapfile
    - mainline
