---
  - name: Install the package vim
    yum: name=vim state=latest

  - name: Install the package git
    yum: name=git state=latest

  - name: Install the package htop
    yum: name=htop state=latest

  - name: Install the package iotop
    yum: name=iotop state=latest

  - name: Install the package byobu
    yum: name=byobu state=latest

  - name: Install the package yum-cron
    yum: name=yum-cron state=latest

  - name: Turn automatic update apply on
    command: sed -ie 's/apply_updates = no/apply_updates = yes/' /etc/yum/yum-cron.conf

  - name: Start the yum-cron service (and enable it on boot)
    service: name=yum-cron state=started enabled=yes

  - name: Install the package lshw
    yum: name=lshw state=latest

  - name: Upgrade all installed packages
    yum: name=* state=latest
