---

  - name: Install the package auter to facilitate updates
    yum: name=auter state=latest
    ignore_errors: yes

  - name: Turn automatic update apply on
    template: src=auter.conf dest=/etc/auter/auter.conf

  - name: Create cron job to run auter --prep hourly
    cron: name="run auter --prep hourly" minute="0" job="/usr/bin/auter --prep"

  - name: Create cron job to run auter --apply hourly
    cron: name="run auter --apply hourly" minute="30" job="/usr/bin/auter --apply"
