---
# https://www.digitalocean.com/community/tutorials/how-to-set-up-a-basic-iptables-firewall-on-centos-6

  - name: Uninstall the firewalld service
    yum: name=firewalld state=removed

  - name: Ensure iptables is installed
    yum: name=iptables state=installed

  - name: Ensure iptables services are installed
    yum: name=iptables-services state=installed

  - name: Configure iptables for additional security
    template: src=iptables dest=/etc/sysconfig/iptables

  - name: Make sure that the iptables service is active (and enabled on boot)
    service: name=iptables state=started enabled=yes

  - name: Load the new iptables rules
    service: name=iptables state=reloaded
