---
# https://www.digitalocean.com/community/tutorials/how-to-set-up-a-basic-iptables-firewall-on-centos-6

  - name: Uninstall the firewalld service
    yum: name=firewalld state=removed

  - name: Ensure iptables is installed
    yum: name=iptables state=installed

  - name: Ensure iptables services are installed
    yum: name=iptables-services state=installed

  - name: Configure iptables for additional security
    template: src=iptables dest=/etc/sysconfig/iptables
#    notify:
#      - Activate new iptables rules
#      - Restart the iptables service

  - name: Activate new iptables rules
    shell: iptables-restore < /etc/sysconfig/iptables

  - name: Restart iptables service
    service: name=iptables state=restarted

  - name: Enable the iptables service at boot time
    service: name=iptables enabled=yes

