---

  - name: Upgrade all installed packages
    apt: name=* state=latest
    when: ansible_facts['os_family'] == "Debian"

  - name: Upgrade all installed packages
    yum: name=* state=latest
    when: ansible_facts['os_family'] == "RedHat"
    
  - include: 'sshd.yml'
  - include: 'firewall.yml'
