---

  - name: Upgrade all installed packages
    apt: name=* state=latest
    
#  - include: 'sshd.yml'
#  - include: 'sudoers.yml'
  - include: 'firewall.yml'
#  - include: 'selinux.yml'
#  - include: 'automatic-updates.yml'
