---
  - name: Install SELinux management dependencies
    yum: name={{ item }} state=present
    with_items:
      - libselinux-python
      - libsemanage-python

  - name: Enable SELinux enforcing for enhanced security
    selinux: policy=targeted state=enforcing

  - name: Restart server so that SELinux is running
    shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for server to come back online
    local_action:
      module: wait_for
       host={{ inventory_hostname }}
       port=22
       delay=10
       state=started
