---
  - name: Configure sshd for additional security
    template: src=sshd_config dest=/etc/ssh/sshd_config

  - name: Restart the sshd service (and make sure it's enabled on boot)
    service: name=sshd state=restarted enabled=yes

