---
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Make sure unattended-upgrades started and enabled
    service: name=unattended-upgrades state=started enabled=yes

  - name: Remove "cloud-init" package
    apt:
      name: cloud-init
      state: absent
