---
  - name: Install desktop packages
    apt:
      pkg:
        - lubuntu-desktop
        - xorg
        - firefox
        - baobab
        - hardinfo
        - lxappearance
        - xrdp
        - xorgxrdp
      state: latest
      update_cache: yes

  - name: Set default target to graphical
    command: systemctl set-default graphical.target

  - name: root .xsession file
    template: src=xsession dest=/root/.xsession owner=root

  - name: dylan .xsession file
    template: src=xsession dest=/home/dylan/.xsession owner=dylan

  - name: Set new_cursors value to false
    command: sed -e 's/^new_cursors=true/new_cursors=false/g' -i /etc/xrdp/xrdp.ini

  - name: Start xrdp
    service: name=xrdp state=started enabled=yes
