---
  - name: Install some select desktop packages
    apt: pkg={{item}} state=latest
    with_items:
     - lubuntu-core
     - xorg
     - tigervnc-standalone-server
     - firefox
     - baobab
     - file-roller
     - galculator
     - hardinfo
     - hexchat
     - imagemagick
     - synaptic
     - transmission-gtk

  - name: Set default target to graphical
    command: systemctl set-default graphical.target

  - name: Make sure dylan has .vnc directory
    file: path=/home/dylan/.vnc/ state=directory mode=0755

  - name: Configure vnc xstartup for dylan
    template: src=xstartup dest=/home/dylan/.vnc/xstartup

