---
  - name: Install desktop packages
    apt:
      pkg:
        - lubuntu-core
        - xorg
        - tigervnc-standalone-server
        - firefox
        - baobab
        - file-roller
        - galculator
        - hardinfo
        - hexchat
        - imagemagick
        - lxappearance
        - synaptic
        - transmission-gtk
      state: latest
      update_cache: yes


  - name: Icon theme
    apt: pkg=adwaita-icon-theme-full state=latest

  - name: Set default target to graphical
    command: systemctl set-default graphical.target

  - name: Make sure dylan has .vnc directory
    file: path=/home/dylan/.vnc/ state=directory mode=0755

  - name: Configure vnc xstartup for dylan
    template: src=xstartup dest=/home/dylan/.vnc/xstartup

