---
  - name: Enable the crond service at boot time
    service: name=crond state=started enabled=yes

  - name: Create cron job to update website contents
    cron: name="periodically update website contents" minute="*/5" job="cd /var/www/dylanmtaylor.com/html; git pull >/dev/null 2>&1"

  - name: Create cron job to update fwc subdomain contents
    cron: name="periodically update fwc subdomain files" minute="*/15" job="cd /var/www/fwc.dylanmtaylor.com/html; git pull >/dev/null 2>&1"

  - name: Create cron job to update apps subdomain contents
    cron: name="periodically update apps subdomain files" minute="*/15" job="cd /var/www/apps.dylanmtaylor.com/html; git pull >/dev/null 2>&1"


