---
  - name: Enable the crond service at boot time
    service: name=cron state=started enabled=yes

  - name: Create cron job to update website contents
    cron: name="periodically update website contents" minute="*/5" job="cd /var/www/dylanmtaylor.com/html; git reset --hard HEAD^; git pull >/dev/null 2>&1"

  - name: Create cron job to update fwc subdomain contents
    cron: name="periodically update fwc subdomain files" minute="*/15" job="docker exec -it fwc-dylanmtaylor-com /usr/bin/git pull 2>&1"

  - name: Create cron job to update apps subdomain contents
    cron: name="periodically update apps subdomain files" minute="*/15" job="docker exec -it apps-dylanmtaylor-com /usr/bin/git pull 2>&1"

  - name: Create cron job to update my resume
    cron: name="periodically update my resume" minute="*/5" job="cd /root/Dylan-Resume; git reset --hard HEAD^; git pull >/dev/null 2>&1; xelatex --output-directory=/var/www/dylanmtaylor.com/html/files dylan-resume.tex; ls /var/www/dylanmtaylor.com/html/files/"


