---
# https://www.digitalocean.com/community/tutorials/how-to-set-up-a-basic-iptables-firewall-on-centos-6

  - name: Uninstall the firewalld service
    yum: name=firewalld state=removed

  - name: Ensure iptables is installed
    yum: name=iptables state=installed

  - name: Ensure iptables services are installed
    yum: name=iptables-services state=installed

  - name: Stop the iptables service
    service: name=iptables state=stopped enabled=yes

  - name: Flush iptables rules
    command: iptables -F

  - name: Block all null packets
    command: iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

  - name: Block all packets with tcp flags NONE
    command: iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP

  - name: Block all XMAS packets
    command: iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

  - name: Allow localhost interface lo
    command: iptables -A INPUT -i lo -j ACCEPT

  - name: Allow webserver traffic on port 80
    command: iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT

  - name: Allow webserver traffic on port 443
    command: iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT

  - name: Allow SSH traffic on port 22
    command: iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT

  - name: Allow outgoing connections
    command: iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

  - name: Accept outgoing by default
    command: iptables -P OUTPUT ACCEPT

  - name: Drop incomming by default
    command: iptables -P INPUT DROP

  - name: Save iptables configuration
    shell: iptables-save > /etc/sysconfig/iptables

  - name: Start the iptables service
    service: name=iptables state=started enabled=yes

  - name: Reload iptables service
    service: name=iptables state=reloaded

  - name: Restart iptables service
    service: name=iptables state=restarted

