---
  - command: fallocate -l 1G /swapfile
    name: allocate a 1 GB swap file at /swapfile
    ignore_errors: yes
    args:
      creates: /swapfile

  - file: path=/swapfile owner=root group=root mode=0600
    ignore_errors: yes
    name: set swap file permissions

  - shell: mkswap /swapfile; mkdir -p /opt/swap; touch /opt/swap/formatted; swapon /swapfile; touch /opt/swap/success
    name: format swap file and enable it
    ignore_errors: yes
    args:
      creates: /opt/swap/formatted

  - shell: if test -e "/opt/swap/success"; then echo "/swapfile   swap    swap    sw  0   0" >> /etc/fstab; touch /opt/swap/fstab; fi
    name: add /swapfile to the /etc/fstab file
    ignore_errors: yes
    args:
      creates: /opt/swap/fstab
