---
  - name: Make sure hostname is set correctly
    hostname: name=dylanmtaylor.com

  - name: Copy my public SSH key for root user
    authorized_key: user=root key="{{ lookup('file', './files/authorized_keys') }}"

  - name: Add group 'dylan'
    group: name=dylan state=present

  - name: Debian -- Add the user 'dylan' with admin rights and a bash shell
    user:
      name: dylan
      comment: "Dylan Taylor"
      shell: /bin/bash
      groups: sudo,dylan
      append: yes
      password: ''
    when: ansible_facts['os_family'] == "Debian"

  - name: Red Hat -- Add the user 'dylan' with admin rights and a bash shell
    user:
      name: dylan
      comment: "Dylan Taylor"
      shell: /bin/bash
      groups: wheel,dylan
      append: yes
      password: ''
    when: ansible_facts['os_family'] == "RedHat"

  - name: Copy my public SSH key for non-root user 'dylan'
    authorized_key: user=dylan key="{{ lookup('file', './files/authorized_keys') }}"
