---
  - name: Make sure that git is installed
    apt: pkg=git state=latest

  - name: Clear out existing website files
    file:
      state: absent
      path: "/var/www/dylanmtaylor.com/html/"

  - name: Ensure directory for website exists
    file: path=/var/www/dylanmtaylor.com/html state=directory

  - name: Retrieve latest version of website files
    unarchive:
      src: https://gitlab.com/dylanmtaylor/dylanmtaylor.gitlab.io/-/jobs/artifacts/master/download?job=pages
      dest: /var/www/dylanmtaylor.com/html/
      remote_src: yes

  - name: Create a symbolic link for /files
    file:
      src: "/var/www/files.dylanmtaylor.com/html/"
      dest: "/var/www/dylanmtaylor.com/html/public/files"
      state: link

  - name: Prevent crazy recursion when setting permissions
    file:
      path: "/var/www/dylanmtaylor.com/html/public/pages"
      state: absent

  - name: Ensure directory for resume exists
    file: path=/root/Dylan-Resume state=directory

  - name: Checkout latest version of resume files from gitlab
    git: repo=https://gitlab.com/dylanmtaylor/Dylan-Resume.git
         dest=/root/Dylan-Resume
         version=HEAD
         update=yes
         force=yes

  - name: Make sure that /var/www has appropriate permissions for Docker to be able to read the files
    file:
      path: /var/www/
      state: directory
      recurse: yes
      owner: root
      group: root
      mode: '0755'
      
  - name: Create a symbolic link for /pages
    file:
      src: "/var/www/html/"
      dest: "/var/www/dylanmtaylor.com/html/public/pages"
      state: link
      force: yes
