---
  - name: Make directory for fwc subdomain contents
    file: path=/usr/share/nginx/fwc.dylanmtaylor.com state=directory mode=0755

  - name: Checkout latest version of fwc subdomain files from github
    git: repo=https://github.com/dylanmtaylor/fwc.dylanmtaylor.com.git
         dest=/usr/share/nginx/fwc.dylanmtaylor.com/
         version=HEAD
         update=yes

