---

  - name: Install the latest versions of utility packages using apt
    apt:
      pkg:
        - asciidoc
        - build-essential
        - certbot
        - curl
        - fio
        - gcc
        - git
        - glances
        - htop
        - iftop
        - ioping
        - iotop
        - iptraf-ng
        - lshw
        - neofetch
        - nmap
        - nmon
        - p7zip-full
        - pngcrush
        - pv
        - setools
        - strace
        - speedtest-cli
        - tcpdump
        - telnet
        - unzip
        - vim
        - wget
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Enable neofetch on login for root
    lineinfile:
      path: /root/.bashrc
      line: '#neofetch --disable packages'
    when: ansible_facts['os_family'] == "Debian"

  - name: Enable neofetch on login for dylan
    lineinfile:
      path: /home/dylan/.bashrc
      line: 'neofetch --disable packages'
    when: ansible_facts['os_family'] == "Debian"

  - name: Install cockpit
    apt:
      pkg:
        - cockpit
        - cockpit-networkmanager
        - cockpit-packagekit
        - cockpit-storaged
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Install cockpit
    yum:
      pkg:
        - cockpit
        - cockpit-networkmanager
        - cockpit-packagekit
        - cockpit-storaged
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Enable cockpit
    systemd:
      name: cockpit.socket
      state: started
      enabled: True
  
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
    when: ansible_facts['os_family'] == "Debian"
