---
  - name: Install the latest versions of utility packages using yum
    yum: pkg={{item}} state=latest
    with_items:
     - asciidoc
     - byobu
     - curl
     - git
     - htop
     - iotop
     - lshw
     - nmap
     - p7zip
     - pngcrush
     - sos
     - telnet
     - unzip
     - vim
     - wget

  - name: Install the latest versions of development packages using yum
    yum: pkg={{item}} state=latest
    with_items:
     - gcc
     - make
     - php-cli
     - python-devel
     - python-pip
     - ruby-devel

  - name: Install the latest version of jekyll using rubygems
    gem: name=jekyll state=latest

  - name: Remove immutable bit from /usr/lib/udev/rules.d/60-net.rules
    command: chattr -i /usr/lib/udev/rules.d/60-net.rules

  - name: Upgrade all installed packages
    yum: name=* state=latest
