---

  - name: Install the latest versions of utility packages using apt
    apt: pkg={{item}} state=latest
    with_items:
     - asciidoc
     - build-essential
     - byobu
     - curl
     - git
     - htop
     - iotop
     - ioping
     - lshw
     - nmap
     - p7zip-full
     - pngcrush
     - setools
     - telnet
     - unzip
     - vim
     - wget
     - fio
     - tcpdump
     - duplicity
     - pv
     - mc
     - glances
     - iftop
     - iptraf-ng
     - nmon
     - yum-utils
     - strace
     - certbot

  - name: Install ruby
    apt: name=ruby state=latest

  - name: Install the latest versions of additional development packages using yum
    apt: pkg={{item}} state=latest
    with_items:
     - gcc
     - php-cli
     - python-dev
     - python3-pip
     - wireless-tools

  - name: Install neofetch
    apt: pkg={{item}} state=latest
    with_items:
     - neofetch

  - name: Enable neofetch on login for root
    lineinfile:
      path: /root/.bashrc
      line: '#neofetch --disable packages'

  - name: Enable neofetch on login for dylan
    lineinfile:
      path: /home/dylan/.bashrc
      line: 'neofetch --disable packages'

  - name: Install speedtest-cli
    pip: name=speedtest-cli
    
  - name: Install glances
    pip: name=glances

  - name: Install the latest version of jekyll using apt
    apt: pkg={{item}} state=latest
    with_items:
     - jekyll

  - name: Install cockpit
    apt: pkg={{item}} state=latest
    with_items:
     - cockpit
     - cockpit-docker
     - cockpit-networkmanager
     - cockpit-packagekit
     - cockpit-storaged

  - name: Enable cockpit
    systemd:
      name: cockpit.socket
      state: started
      enabled: True
