---

  - name: Install the latest versions of utility packages using apt
    apt:
      pkg:
        - asciidoc
        - build-essential
        - byobu
        - certbot
        - curl
        - duplicity
        - fio
        - gcc
        - git
        - glances
        - htop
        - iftop
        - ioping
        - iotop
        - iptraf-ng
        - lshw
        - mc
        - neofetch
        - nmap
        - nmon
        - p7zip-full
        - php-cli
        - pngcrush
        - pv
        - python3-pip
        - python-dev
        - setools
        - strace
        - tcpdump
        - telnet
        - unzip
        - vim
        - wget
        - wireless-tools
      state: latest
      update_cache: yes

  - name: Install ruby
    apt: name=ruby state=latest

  - name: Enable neofetch on login for root
    lineinfile:
      path: /root/.bashrc
      line: '#neofetch --disable packages'

  - name: Enable neofetch on login for dylan
    lineinfile:
      path: /home/dylan/.bashrc
      line: 'neofetch --disable packages'

  - name: Install speedtest-cli
    pip: name=speedtest-cli
    
  - name: Install glances
    pip: name=glances

  - name: Install the latest version of jekyll using apt
    apt: pkg=jekyll state=latest

  - name: Install cockpit
    apt:
      pkg:
        - cockpit
        - cockpit-docker
        - cockpit-networkmanager
        - cockpit-packagekit
        - cockpit-storaged
      state: latest
      update_cache: yes

  - name: Enable cockpit
    systemd:
      name: cockpit.socket
      state: started
      enabled: True
