---
  - name: Install python3 and pip packages (dependencies)
    apt:
      pkg:
        - python3
        - python3-pip
      state: latest
      update_cache: yes

  - name: Install docker
    shell: curl -sSL https://get.docker.com/ | sh
    args:
      creates: /usr/bin/docker
      
  - name: Install setuptools
    pip: name=setuptools
    
  - name: Install docker python module
    pip: name=docker state=latest

  - name: Start Docker
    service: name=docker state=started enabled=yes

  - name: Prune pre-existing docker resources
    command: docker system prune -a -f

  - name: Pull Nginx image
    docker_image:
      name: nginx
      source: pull

  - name: Pull Nginx proxy image
    docker_image:
      name: jwilder/nginx-proxy:alpine
      source: pull

  - name: Pull redirect image
    docker_image:
      name: 'cusspvz/redirect:latest'
      source: pull
      
  - name: Pull nginx-php-fpm image
    docker_image:
      name: 'richarvey/nginx-php-fpm:latest'
      source: pull

  - name: Restart service docker, in all cases
    service:
      name: docker
      state: restarted

  - name: Run nginx-proxy
    docker_container:
      name: 'nginx-proxy'
      image: 'jwilder/nginx-proxy:alpine'
      state: 'started'
      restart_policy: 'always'
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        
  - name: Run main website
    docker_container:
      name: 'www-dylanmtaylor-com'
      image: 'richarvey/nginx-php-fpm:latest'
      state: 'started'
      restart_policy: 'always'
      env:
        VIRTUAL_HOST: 'www.dylanmtaylor.com,dylanmtaylor.com,dylanmtaylor.local,localhost'
      volumes:
        - /var/www/files.dylanmtaylor.com/html/:/var/www/files.dylanmtaylor.com/html/:ro
        - /var/www/dylanmtaylor.com/html/public/:/var/www/html/:ro
        - /var/www/errors/404.html:/var/www/errors/404.html:ro

  - name: Run apps website
    docker_container:
      name: 'apps-dylanmtaylor-com'
      image: 'richarvey/nginx-php-fpm:latest'
      state: 'started'
      restart_policy: 'always'
      env:
        GIT_NAME: "Dylan M. Taylor"
        GIT_EMAIL: "dylan@dylanmtaylor.com"
        GIT_REPO: https://gitlab.com/dylanmtaylor/apps-dylanmtaylor-com.git
        VIRTUAL_HOST: 'apps.dylanmtaylor.com,apps.dylanmtaylor.local'
      volumes:
        - /var/www/errors/404.html:/var/www/errors/404.html:ro

  - name: Run fwc website
    docker_container:
      name: 'fwc-dylanmtaylor-com'
      image: 'richarvey/nginx-php-fpm:latest'
      state: 'started'
      restart_policy: 'always'
      env:
        GIT_NAME: "Dylan M. Taylor"
        GIT_EMAIL: "dylan@dylanmtaylor.com"
        GIT_REPO: https://gitlab.com/dylanmtaylor/fwc-dylanmtaylor-com.git
        VIRTUAL_HOST: 'fwc.dylanmtaylor.com,fwc.dylanmtaylor.local'
      volumes:
        - /var/www/errors/404.html:/var/www/errors/404.html:ro

  - name: Run files website
    docker_container:
      name: 'files-dylanmtaylor-com'
      image: 'nginx:alpine'
      state: 'started'
      restart_policy: 'always'
      env:
        VIRTUAL_HOST: 'files.dylanmtaylor.com,files.dylanmtaylor.local'
      volumes:
        - /var/www/files.dylanmtaylor.com/html/:/usr/share/nginx/html:ro

  - name: Run git website
    docker_container:
      name: 'git-dylanmtaylor-com'
      image: 'cusspvz/redirect:latest'
      state: 'started'
      restart_policy: 'always'
      env:
        VIRTUAL_HOST: 'git.dylanmtaylor.com,git.dylanmtaylor.local'
        REDIRECT: 'https://gitlab.com/dylanmtaylor'
        
  - name: Run blog website
    docker_container:
      name: 'blog-dylanmtaylor-com'
      image: 'cusspvz/redirect:latest'
      state: 'started'
      restart_policy: 'always'
      env:
        VIRTUAL_HOST: 'blog.dylanmtaylor.com,blog.dylanmtaylor.local'
        REDIRECT: 'https://dylanmtaylor.com/blog'
        
