---
  - name: Install packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - git
      - wget
      - curl
      - python3
      - python3-pip

  - name: Install docker
    shell: curl -sSL https://get.docker.com/ | sh
    args:
      creates: /usr/bin/docker

  - name: Install docker-py
    pip: name=docker-py version=1.1.0
  
  - name: Start Docker
    service: name=docker state=started enabled=yes
