---
  - name: Install packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - git
      - wget
      - curl
      - python3
      - python3-pip

  - name: Install docker
    shell: curl -sSL https://get.docker.com/ | sh
    args:
      creates: /usr/bin/docker
      
  - name: Install setuptools
    pip: name=setuptools
    
  - name: Install docker python module
    pip: name=docker version=2.0.0
  
  - name: Start Docker
    service: name=docker state=started enabled=yes
    
  - name: Pull Nginx image
    docker_image:
      name: nginx
      source: pull

  - name: Pull Nginx proxy image
    docker_image:
      name: jwilder/nginx-proxy
      source: pull

  - name: Run nginx-proxy
    docker_container:
      name: 'nginx-proxy'
      image: 'jwilder/nginx-proxy'
      state: 'started'
      restart_policy: 'always'
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        
  - name: Run main website
    docker_container:
      name: 'www-dylanmtaylor-com'
      image: 'nginx'
      state: 'started'
      restart_policy: 'always'
      env:
        VIRTUAL_HOST: 'www.dylanmtaylor.com,dylanmtaylor.com,dylanmtaylor.local'
      volumes:
        - /var/www/dylanmtaylor.com/html/:/usr/share/nginx/html:ro
        

